pypi-torchmetrics: Autospec creation for update from version 1.0.3 to version 1.1.0
Bojan Todorkov (1):
      Add Visual Information Fidelity (#1830)

Changsheng Quan (1):
      Add Source-Aggregated Signal-to-Distortion Ratio (SA-SDR) (#1882)

Fansure Grin (1):
      Fix computing iou when there have empty predicted boxes (#1892)

Ian Maquignaz (2):
      Fixed CLIPScore import in docs (#1943)
      Fixed typo in docs (#1944)

Jirka (8):
      chlog: new section
      drop redundant isort config
      ci/docs: minor rename
      update chlog after `1.0.3`
      pypi download badge
      ci: docs check skipp draft
      ci: merge general checks | v0.9.0
      releasing 1.1.0

Jirka B (5):
      make env with FREEZE_REQUIREMENTS
      chlog: fix year typo
      chlog update after `1.0.2`
      rtfd: drop building docs as PDF
      ci/docs: bump timeout to 45m

Jirka Borovec (15):
      ci/pypi: move delay between test and final
      ci/pypi: skip job instead of steps
      ci/gpu: install missing pkgs (#1885)
      pyupgrade: 3.8+ (#1912)
      docformatter: config with black (#1909)
      docs: resolving relative path to images (#1930)
      revert sphinx to `5.3` to recover icon with anchor links (#1956)
      building docs with py3.9 (#1958)
      docs: revert links in gallery & adjust img/icon path (#1964)
      docs: fix math render with legacy sphinx 5.3 (#1973)
      ci/docs: split links testing and build (#1975)
      enable pygrep-hooks with precommit (#1992)
      docs: enable Sphinx nitpicky & fixing refs (#1916)
      refactor usage of manual seed (#2007)
      ci: check links in all MD files (#2012)

Katsuya (1):
      Fix AttributeError: module 'matplotlib' has no attribute 'axes' (#1955)

Luca Di Liello (1):
      Adding MRR@K as an option to MRR (#1961)

Marçal Comajoan Cara (1):
      Improve warning message (#1934)

Nicki Skafte Detlefsen (34):
      Fix doc links (#1881)
      Hotfix for CI docs (#1894)
      Fix `Auroc` metric when `max_fpr` is set and a class is missing (#1895)
      Fix meanmetric broadcasting for Nan values (#1898)
      Bugfix for using metric collection and aggregation metric (#1896)
      Fix expected box format by pycoco (#1913)
      Feature: Base wrapper class (#1901)
      New section in changelog after 1.0.1 (#1920)
      Typing (n+1)/m (#1925)
      Add warning on small input in `PearsonCorrCoef` (#1926)
      Fix prefix/postfix interaction between `MetricCollection` and `ClasswiseWrapper` (#1918)
      Fix precision issue in calibration error (#1919)
      New metric: `EditDistance` (#1906)
      Set min transformers version when importing (#1947)
      Prune unused imports & cleaning (#1954)
      docs: remove empty `(,,,)` from plots docstrings (#1965)
      Fix missing AUC score when plotting (#1948)
      Convert classification wrapper to metrics (#1963)
      Fix external linking in docs (#1980)
      Warning on many detections in `MeanAveragePrecision` (#1978)
      Update docs related to nominal docs (#1979)
      Fix axes in confusion matrix (#1976)
      Fix small mistakes in docs (#1984)
      Fix support for `int` input for samplewise classification (#1977)
      Feature: multioutput mse (#1937)
      Fix example in README file (#1981)
      Add option for extended summary in `MeanAveragePrecision` (#1983)
      `MeanAveragePrecision` box and segm at same time (#1928)
      New metric: Perceptual Path Length (#1939)
      Remove noindex for docs (#1998)
      Warning for CLIP Score on long captions (#2001)
      New metric: CLIP IQA (#1931)
      Docs on memory management (#2006)
      Use lightning utils `apply_to_collection` (#2013)

Shengwei An (1):
      docs: fix typo in SSIM (#1986)

Vivswan Shah (1):
      iou compute in cuda fix (#1982)

dependabot[bot] (12):
      build(deps): update matplotlib requirement from <=3.7.1,>=3.2.0 to >=3.2.0,<=3.7.2 in /requirements (#1903)
      build(deps): bump pytest-rerunfailures from 11.1.2 to 12.0 in /requirements (#1902)
      build(deps): update sewar requirement from <=0.4.5,>=0.4.4 to >=0.4.4,<=0.4.6 in /requirements (#1957)
      build(deps): bump pypa/gh-action-pypi-publish from 1.8.7 to 1.8.8 (#1967)
      build(deps): update kornia requirement from <0.6.13,>=0.6.7 to >=0.6.7,<0.7.1 in /requirements (#1985)
      build(deps): update tqdm requirement from <=4.65.0,>=4.41.0 to >=4.41.0,<=4.66.1 in /requirements (#1996)
      build(deps): bump mypy from 1.4.1 to 1.5.0 in /requirements (#1997)
      build(deps): bump pytest-doctestplus from 0.13.0 to 1.0.0 in /requirements (#1995)
      build(deps): update pycocotools requirement from <=2.0.6,>2.0.0 to >2.0.0,<=2.0.7 in /requirements (#1994)
      build(deps): bump mypy from 1.5.0 to 1.5.1 in /requirements (#2010)
      build(deps): bump coverage from 7.2.7 to 7.3.0 in /requirements (#2011)
      build(deps): update regex requirement from <=2023.6.3,>=2021.9.24 to >=2021.9.24,<=2023.8.8 in /requirements (#2009)